/**
 * pdf.js
 * Payroll receipt PDF generation using jsPDF and jspdf-autotable.
 * Generates professional receipts with the Salden logo for each
 * batch payment transaction.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import logoUrl from "../assets/logo.png";

/**
 * Generates a PDF payroll receipt for a given batch payment.
 * @param {object} params
 * @param {string} params.employer - Employer wallet address (full)
 * @param {string} params.cloneAddress - Payroll contract address
 * @param {string} params.txHash - Transaction hash
 * @param {string} params.date - Human-readable date
 * @param {Array<{employee: string, amount: string}>} params.employees - Per-employee breakdown
 * @param {string} params.totalAmount - Total USDC paid
 * @param {string} params.receiptNumber - e.g. "1"
 */
export function generatePayrollReceiptPDF({
  employer,
  cloneAddress,
  txHash,
  date,
  employees,
  totalAmount,
  receiptNumber,
}) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = margin;

  // ─── Header ───────────────────────────────────────────────────────────────

  // Salden Logo
  try {
    doc.addImage(logoUrl, "JPEG", margin, y, 28, 14);
  } catch {
    // If logo fails, continue without it
  }

  // "SALDEN" text header
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(6, 11, 24);
  doc.text("SALDEN", margin + 32, y + 9);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("Decentralized Payroll", margin + 32, y + 14);

  // "PAYROLL RECEIPT" on the right
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("PAYROLL RECEIPT", pageWidth - margin, y + 6, { align: "right" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`#${receiptNumber}`, pageWidth - margin, y + 12, { align: "right" });
  doc.text(date, pageWidth - margin, y + 17, { align: "right" });

  y += 22;

  // Divider
  doc.setDrawColor(30, 45, 74);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ─── Transaction Summary ──────────────────────────────────────────────────

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(6, 11, 24);
  doc.text("Transaction Summary", margin, y);
  y += 7;

  const summaryFields = [
    ["Employer Wallet", employer],
    ["Payroll Contract", cloneAddress || "N/A"],
    ["Transaction Hash", txHash],
    ["Total Employees Paid", employees.length.toLocaleString()],
    ["Total Amount Paid", `${totalAmount} USDC`],
    ["Status", "Confirmed on Arc Testnet"],
  ];

  doc.setFontSize(9);
  for (const [label, value] of summaryFields) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(71, 85, 105);
    doc.text(`${label}:`, margin, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(6, 11, 24);

    // Wrap long values (addresses, hashes)
    const displayValue =
      value.length > 60 ? doc.splitTextToSize(value, pageWidth - margin * 2 - 50) : value;
    doc.text(displayValue, margin + 50, y);
    y += typeof displayValue === "string" ? 6 : displayValue.length * 5 + 1;
  }

  y += 4;
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ─── Per-Employee Breakdown ───────────────────────────────────────────────

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(6, 11, 24);
  doc.text("Employee Payment Breakdown", margin, y);
  y += 5;

  const tableRows = employees.map((emp, idx) => [
    (idx + 1).toString(),
    emp.employee, // Full address
    `${emp.amount} USDC`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["#", "Employee Wallet Address", "Amount Paid (USDC)"]],
    body: tableRows,
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 30, 30],
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 110, font: "courier" },
      2: { cellWidth: 40, halign: "right" },
    },
    margin: { left: margin, right: margin },
  });

  // ─── Footer ───────────────────────────────────────────────────────────────

  const finalY = doc.lastAutoTable.finalY + 10;
  const footerY = Math.min(finalY, doc.internal.pageSize.getHeight() - 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Generated by Salden — Decentralized Payroll on Arc Network Testnet",
    pageWidth / 2,
    footerY,
    { align: "center" }
  );
  doc.text(
    "This receipt is generated from on-chain transaction data and is cryptographically verifiable.",
    pageWidth / 2,
    footerY + 5,
    { align: "center" }
  );

  // Save the PDF
  const fileName = `Salden_Payroll_Receipt_${receiptNumber}_${date.replace(/[\s,]/g, "_")}.pdf`;
  doc.save(fileName);
}
